// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _extauth from "./ext/auth";
export type $AccountType = {
  "bank": $.$expr_Literal<$AccountType>;
  "cash": $.$expr_Literal<$AccountType>;
} & $.EnumType<"default::AccountType", ["bank", "cash"]>;
const AccountType: $AccountType = $.makeType<$AccountType>(_.spec, "80e102ff-f70a-11ef-9f4b-6311814e8a37", _.syntax.literal);

export type $CurrencyType = {
  "CAD": $.$expr_Literal<$CurrencyType>;
  "EUR": $.$expr_Literal<$CurrencyType>;
  "MXN": $.$expr_Literal<$CurrencyType>;
  "USD": $.$expr_Literal<$CurrencyType>;
} & $.EnumType<"default::CurrencyType", ["CAD", "EUR", "MXN", "USD"]>;
const CurrencyType: $CurrencyType = $.makeType<$CurrencyType>(_.spec, "f2153688-fd1b-11ef-9169-c92219e550e3", _.syntax.literal);

export type $EntryType = {
  "expense": $.$expr_Literal<$EntryType>;
  "income": $.$expr_Literal<$EntryType>;
  "withdrawal": $.$expr_Literal<$EntryType>;
} & $.EnumType<"default::EntryType", ["expense", "income", "withdrawal"]>;
const EntryType: $EntryType = $.makeType<$EntryType>(_.spec, "80e11b72-f70a-11ef-a93d-c18632c5b734", _.syntax.literal);

export type $CurrencyλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "symbol": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "value": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "code": $.PropertyDesc<$CurrencyType, $.Cardinality.One, false, false, false, false>;
}>;
type $Currency = $.ObjectType<"default::Currency", $CurrencyλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Currency">;
const $Currency = $.makeType<$Currency>(_.spec, "8a26e1fc-f70a-11ef-8721-ddb397e10907", _.syntax.literal);

const Currency: $.$expr_PathNode<$.TypeSet<$Currency, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Currency, $.Cardinality.Many), null);

export type $EntryλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "account": $.PropertyDesc<$AccountType, $.Cardinality.One, false, false, false, false>;
  "amount": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "category": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "type": $.PropertyDesc<$EntryType, $.Cardinality.One, false, false, false, false>;
  "enteredAmount": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "enteredCurrency": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "created": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "user": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "<entries[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<entries": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Entry = $.ObjectType<"default::Entry", $EntryλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Entry">;
const $Entry = $.makeType<$Entry>(_.spec, "80e136a6-f70a-11ef-b675-37ad4fedecc7", _.syntax.literal);

const Entry: $.$expr_PathNode<$.TypeSet<$Entry, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Entry, $.Cardinality.Many), null);

export type $InvitationλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "accepted": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "sent": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
  "from": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "to": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Invitation = $.ObjectType<"default::Invitation", $InvitationλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Invitation">;
const $Invitation = $.makeType<$Invitation>(_.spec, "80e6e04a-f70a-11ef-be78-e1dc35b13d52", _.syntax.literal);

const Invitation: $.$expr_PathNode<$.TypeSet<$Invitation, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Invitation, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "is_admin": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.AtLeastOne, {}, true, false,  false, false>;
  "partners": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "entries": $.LinkDesc<$Entry, $.Cardinality.Many, {}, false, true,  false, false>;
  "<partners[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user[is Entry]": $.LinkDesc<$Entry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<from[is Invitation]": $.LinkDesc<$Invitation, $.Cardinality.Many, {}, false, false,  false, false>;
  "<to[is Invitation]": $.LinkDesc<$Invitation, $.Cardinality.Many, {}, false, false,  false, false>;
  "<from": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<partners": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<to": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {identity: {__element__: _extauth.$Identity, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {email: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::User">;
const $User = $.makeType<$User>(_.spec, "80e32bd5-f70a-11ef-94d7-43ff6af0567f", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { AccountType, CurrencyType, EntryType, $Currency, Currency, $Entry, Entry, $Invitation, Invitation, $User, User };

type __defaultExports = {
  "AccountType": typeof AccountType;
  "CurrencyType": typeof CurrencyType;
  "EntryType": typeof EntryType;
  "Currency": typeof Currency;
  "Entry": typeof Entry;
  "Invitation": typeof Invitation;
  "User": typeof User
};
const __defaultExports: __defaultExports = {
  "AccountType": AccountType,
  "CurrencyType": CurrencyType,
  "EntryType": EntryType,
  "Currency": Currency,
  "Entry": Entry,
  "Invitation": Invitation,
  "User": User
};
export default __defaultExports;
